### ISSUE TITLE
Dataset creation

### ISSUE THREAD

**Issue by karim23657** [SadeghKrmi/pertts-streamlit#1]
@SadeghKrmi , Hello

Could you please a share a tutorial how did you created your dataset ?

**Comment by SadeghKrmi** [comment]
I used the ljspeech format to create the dataset, as it is the most used dataset type.

**Comment by SadeghKrmi** [comment]
Sure, I would like to add more contributors on creating a close-to-perfect Persian/Farsi TTS, I'll try to record a video on how to gather data and train, and we can also set up meetings with other contributors online, willing to contribute to start creating something close-to-perfect.

Please join https://discord.gg/JerZTvVK
