### ISSUE TITLE
Help for creating dataset

### ISSUE THREAD

**Issue by karim23657** [SadeghKrmi/pertts-streamlit#2]
Thank you @SadeghKrmi , i wanted to know these about your dataset creation process :

- how did you get transcription of rokhpodcast.ir audio tracks?    
- how did aligned voice with transcription?
- Size of dataset?
- tools you used for creating your dataset?

**Comment by SadeghKrmi** [comment]
Sure, I would like to add more contributors on creating a close-to-perfect Persian/Farsi TTS. It is not easy to explain end-to-end everything. 

- how did you get transcription of rokhpodcast.ir audio tracks?
_for voice transcription, I am using Subtitle Edit tools, to align text with voice, then I am splitting the audio, based on the aligned subtitle in xml format._

- how did aligned voice with transcription?
_I am usign the auto generated subtitle and also it's youtube channel._

- Size of dataset?
10 hours.
tools you used for creating your dataset?
_python script, Subtitle Edit_

I'll try to record a video on how to gather data and train, and we can also set up meetings with other contributors online, willing to contribute to start creating something close-to-perfect.

Please join https://discord.gg/JerZTvVK if you'd like to get in touch and collaborate more :)
