### ISSUE TITLE
training new model?

### ISSUE THREAD

**Issue by lumos675** [SadeghKrmi/pertts-streamlit#8]
how to train new model for this?

**Comment by SadeghKrmi** [comment]
Use https://github.com/rhasspy/piper, and the latest pertts model in https://huggingface.co/rhasspy/piper-voices/tree/main/fa/fa_IR/amir/medium and training using your training set.

**Comment by lumos675** [comment]
Is it possible to make a complete video step by step and upload on youtube to help people out. I think the biggest problem in your code is that you never teach how to use them so we can grow the community. if we are doing open source we need to teach eachother so we can also have bigger community of coders and programmers. I am not saying you have to do this just it's an idea!

**Comment by SadeghKrmi** [comment]
@lumos675 , I wish I was able to record the video training, but for the time being, I am not able due to other tasks on daily basis.
